# Generated by Django 6.0.2 on 2026-02-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.IntegerField()),
                ('address', models.CharField(max_length=500)),
                ('dob', models.DateTimeField()),
                ('profile_image', models.ImageField(upload_to='static/asset')),
                ('bg_image', models.ImageField(blank=True, null=True, upload_to='static/asset/')),
                ('facebook', models.URLField(max_length=300)),
                ('linkedin', models.URLField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_image', models.ImageField(upload_to='static/asset')),
                ('service_title', models.CharField(max_length=300)),
            ],
        ),
    ]
