# Generated by Django 6.0.2 on 2026-02-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_date', models.DateField()),
                ('blog_image', models.ImageField(upload_to='static/asset/')),
                ('blog_title', models.CharField(max_length=200)),
                ('blog_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField()),
                ('address', models.CharField(max_length=500)),
                ('dob', models.DateTimeField()),
                ('profile_image', models.ImageField(upload_to='static/asset')),
                ('bg_image', models.ImageField(blank=True, null=True, upload_to='static/asset/')),
                ('facebook', models.URLField(max_length=300)),
                ('linkedin', models.URLField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=300)),
                ('project_image', models.ImageField(upload_to='static/asset/')),
                ('project_desc', models.CharField(max_length=300)),
                ('project_link', models.URLField(max_length=300)),
                ('project_duration', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_image', models.ImageField(upload_to='static/asset')),
                ('service_title', models.CharField(max_length=300)),
            ],
        ),
    ]
