# Generated by Django 6.0.2 on 2026-02-13 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='enq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=300)),
                ('email', models.TextField(max_length=300)),
                ('mobile', models.IntegerField(max_length=20)),
                ('massage', models.TextField(max_length=300)),
            ],
        ),
    ]
