# Generated by Django 6.0.2 on 2026-02-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_enq'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='enq',
            name='mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bg_image',
            field=models.ImageField(default='', upload_to='static/asset/'),
            preserve_default=False,
        ),
    ]
