# Generated by Django 5.2.11 on 2026-02-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_blog_profile_enq_profile_project_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enq',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
    ]
